//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Automation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiralama
    {
        public int Id { get; set; }
        public int KitapId { get; set; }
        public int CalisanId { get; set; }
        public int MusteriId { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<bool> Aktif { get; set; }
    
        public virtual Calisan Calisan { get; set; }
        public virtual Kitap Kitap { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
