//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Automation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseContext : DbContext
    {
        public DatabaseContext()
            : base("name=LibraryAutomationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Calisan> Calisan { get; set; }
        public virtual DbSet<Kiralama> Kiralama { get; set; }
        public virtual DbSet<Kitap> Kitap { get; set; }
        public virtual DbSet<KitapTur> KitapTur { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
